### ISSUE TITLE
sorry its not an issue i just dont know how to copntact you with a question

### ISSUE THREAD

**Issue by allnamesaregoneallready** [MrLinford/Docker-MediaInfo-PreReq#1]
i think thats exactly what i need to get the correct info in my emby. is there any chance you write your how to description for another set-up (mine ;) 
i'm no it guy, i dont understand a word of it, i have to go step by step to get the cake. I'm on synology nas and my emby is running in a docker. i read for the mediainfo plugon i need mediainfoCLI running also. and thats what your script is for?
many thanks for your feedback!!!!

**Comment by MrLinford** [comment]
Sorry, I only just read this.

The docker container must be this one: https://github.com/linuxserver/docker-emby

You then need to download my script to the mounted volume for that container, and then run the commands.

Sorry, I don't have access to Synology so I can't give you a more step-by-step guide.
